name: Prod test
on:
    workflow_run:
      workflows: ["Prod build"]
      types:
        - completed
jobs:
    build:
        timeout-minutes: 30 # nothing good happens after 30 minutes
        name: Shopify Prod Build
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                node-version: 16

            - name: Cache node_modules
              uses: actions/cache@v3
              id: cache-node-modules
              with:
                path: |
                  node_modules
                key: modules-${{ hashFiles('package-lock.json') }}

            - name: testing
              run: echo testing...


            - name: Slack Notification
              uses: rtCamp/action-slack-notify@v2
              env:
                SLACK_CHANNEL: general
                SLACK_COLOR: 'good' # or a specific color like 'good' or '#ff00ff'
                SLACK_ICON: https://github.com/rtCamp.png?size=48
                SLACK_MESSAGE: 'Post Content :rocket:'
                SLACK_TITLE: Slack Notify
                SLACK_USERNAME: rtCamp
                SLACK_WEBHOOK: https://hooks.slack.com/services/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
            