name: Prod test
on:
    workflow_run:
      workflows: ["Prod build"]
      types:
        - completed
jobs:
    build:
        timeout-minutes: 30 # nothing good happens after 30 minutes
        name: Shopify Prod Build
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                node-version: 16

            - name: Cache node_modules
              uses: actions/cache@v3
              id: cache-node-modules
              with:
                path: |
                  node_modules
                key: modules-${{ hashFiles('package-lock.json') }}

            - name: testing
              run: echo testing...
            